### ISSUE TITLE
卡在PVP界面无法排队

### ISSUE THREAD

**Issue by ychy00001** [Jai-wei/Gw2AutoPvp#10]
非常感谢作者这么好的项目。目前配置了环境变量，运行程序无任何报错，执行第一次匹配，点击pvp按钮后，后续的操作都无法执行，没法点击到排队匹配的按钮。

人物位置：迷雾之心大厅传送点

显示器分辨率：2560*1440
缩放：100%

游戏DPI缩放：取消勾选
伽马：1
界面：普通
游戏分辨率：窗口全屏

是什么地方配置有误么？还是分辨率的问题。

**Comment by Jai-wei** [comment]
游戏分辨率：窗口全屏 ×
必须窗口模式 √

**Comment by ychy00001** [comment]
> 游戏分辨率：窗口全屏 × 必须窗口模式 √

thx！ It works
