### ISSUE TITLE
系统找不到指定的文件是咋回事，我下载的是编译版本，环境变量也添加了，显示的是找不到aibot

### ISSUE THREAD

**Issue by LeopoldJoshua** [Jai-wei/Gw2AutoPvp#2]

**Comment by Jai-wei** [comment]
确保环境变量添加到了`系统变量`的`PATH`中后，如果还报错缺少dll，可在[Release](https://github.com/Jai-wei/Gw2AutoPvp/releases/tag/update)中下载`VC_redist.x64.exe`，安装运行库。
