### ISSUE TITLE
可以更新下10.18的源码吗？

### ISSUE THREAD

**Issue by kohyzsc123** [Jai-wei/Gw2AutoPvp#8]
10.18编译的release可执行文件已更新，源码未更新，已编译exe的基址在我电脑上无效，想自行更改，还请大佬更新下10.18的源码变更情况，谢谢！

**Comment by adgad2** [comment]
看作者一直没更新，我今天我也想回去自己改来着。

lz用现在的代码改了基址不生效吗？

**Comment by Jai-wei** [comment]
> 看作者一直没更新，我今天我也想回去自己改来着。
> 
> lz用现在的代码改了基址不生效吗？

2023.10.23已更新

**Comment by kohyzsc123** [comment]
> 可执行文档2023.10.23已更新。源码目前不再更新，发现有人盗取代码将软件改为月卡收费制。

总有蛀虫啃噬着伟大的开源，感谢。

**Comment by kohyzsc123** [comment]
请问KX现在是否有群？出差1个月回来一看kook和Q都没了  @Jai-wei

**Comment by adgad2** [comment]
> > 看作者一直没更新，我今天我也想回去自己改来着。
> > lz用现在的代码改了基址不生效吗？
> 
> 2023.10.23已更新

好像有bug，第一把ok，第二把会一直卡在成就页面不动

**Comment by kohyzsc123** [comment]
> > > 看作者一直没更新，我今天我也想回去自己改来着。
> > > lz用现在的代码改了基址不生效吗？
> > 
> > 
> > 2023.10.23已更新
> 
> 好像有bug，第一把ok，第二把会一直卡在成就页面不动

未出现此问题

**Comment by Jai-wei** [comment]
> > > 看作者一直没更新，我今天我也想回去自己改来着。
> > > lz用现在的代码改了基址不生效吗？
> > 
> > 
> > 2023.10.23已更新
> 
> 好像有bug，第一把ok，第二把会一直卡在成就页面不动

检查桌面缩放是否设置为100%。详细按照使用说明来设置

**Comment by xunyangjian1** [comment]
他在什么地方收费，我们去举报他

**Comment by adgad2** [comment]
> > > > 看作者一直没更新，我今天我也想回去自己改来着。
> > > > lz用现在的代码改了基址不生效吗？
> > > 
> > > 
> > > 2023.10.23已更新
> > 
> > 
> > 好像有bug，第一把ok，第二把会一直卡在成就页面不动
> 
> 检查桌面缩放是否设置为100%。详细按照使用说明来设置

不好意思，应该确实是我游戏设置问题，不小心打开了dpi缩放

**Comment by adgad2** [comment]
> > > > 看作者一直没更新，我今天我也想回去自己改来着。
> > > > lz用现在的代码改了基址不生效吗？
> > > 
> > > 
> > > 2023.10.23已更新
> > 
> > 
> > 好像有bug，第一把ok，第二把会一直卡在成就页面不动
> 
> 未出现此问题

你们都不会吗，我修改完后又出现了，有时候是第二把第三把，有时候是第五把，总之会时不时地出现，很奇怪

能说一下这个结束一场，返回主城之后会做什么事情，如何做的吗？  @Jai-wei
