### ISSUE TITLE
脚本运行一段时间失效

### ISSUE THREAD

**Issue by tekkz123** [Jai-wei/Gw2AutoPvp#9]
脚本运行一段时间后失效，聊天框显示请立即移动，然后账号pvp被冻结

**Comment by GlassySkyyyy** [comment]
我今天使用这个脚本 选取队长模式以后 对话框显示正在开始第一场比赛 但是游戏里并不会开始排队

**Comment by Jai-wei** [comment]
> 脚本运行一段时间后失效，聊天框显示请立即移动，然后账号pvp被冻结

账号冻结/封号与‘聊天框显示请立即移动’无关，‘聊天框显示请立即移动’是由于长时间没有操作，游戏自动下线。脚本不会自动下一局的问题正在修复。

**Comment by Jai-wei** [comment]
> 我今天使用这个脚本 选取队长模式以后 对话框显示正在开始第一场比赛 但是游戏里并不会开始排队

更新脚本，每次游戏更新 脚本都要更新。。

**Comment by Jai-wei** [comment]
> > 脚本运行一段时间后失效，聊天框显示请立即移动，然后账号pvp被冻结
> 
> 账号冻结/封号与‘聊天框显示请立即移动’无关，‘聊天框显示请立即移动’是由于长时间没有操作，游戏自动下线。脚本不会自动下一局的问题正在修复。

已修复，下载最新版

**Comment by WJZhen** [comment]
> > > 脚本运行一段时间后失效，聊天框显示请立即移动，然后账号pvp被冻结
> > 
> > 
> > 账号冻结/封号与‘聊天框显示请立即移动’无关，‘聊天框显示请立即移动’是由于长时间没有操作，游戏自动下线。脚本不会自动下一局的问题正在修复。
> 
> 已修复，下载最新版

16日最新版出现同样问题，导致pvp被封24h

**Comment by Jai-wei** [comment]
> > > > 脚本运行一段时间后失效，聊天框显示请立即移动，然后账号pvp被冻结
> > > 
> > > 
> > > 账号冻结/封号与‘聊天框显示请立即移动’无关，‘聊天框显示请立即移动’是由于长时间没有操作，游戏自动下线。脚本不会自动下一局的问题正在修复。
> > 
> > 
> > 已修复，下载最新版
> 
> 16日最新版出现同样问题，导致pvp被封24h

详细描述问题。是进入匹配以后，在比赛地图站着不动，还是完成一局以后，在迷雾之地不开始排位导致提示‘聊天框显示请立即移动’，进而自动下线？

**Comment by tekkz123** [comment]
> > > > 脚本运行一段时间后运行，聊天框显示请立即移动，然后账号pvp被冻结
> > > 
> > > 
> > > 账号冻结/封号与'聊天框显示请立即移动'无关，'聊天框显示请立即移动'是由于长时间没有操作，游戏自动下线。脚本不会自动下一局的问题正在修复。
> > 
> > 
> > 已修复，下载最新版本
> 
> 16日最新版本出现同样问题，导致pvp被封24h

**Comment by tekkz123** [comment]
> > > > 脚本运行一段时间后运行，聊天框显示请立即移动，然后账号pvp被冻结
> > > 
> > > 
> > > 账号冻结/封号与'聊天框显示请立即移动'无关，'聊天框显示请立即移动'是由于长时间没有操作，游戏自动下线。脚本不会自动下一局的问题正在修复。
> > 
> > 
> > 已修复，下载最新版本
> 
> 16日最新版本出现同样问题，导致pvp被封24h

你可以再额外添加一个单技能鼠标宏，比如10秒用一次2技能，只要能保证自己能死掉就行，这样有时候网络波动之类原因导致的脚本失效可以保证你当局游戏不会挂机结束，就不会导致封禁了

**Comment by Jai-wei** [comment]
> > > > > 脚本运行一段时间后运行，聊天框显示请立即移动，然后账号pvp被冻结
> > > > 
> > > > 
> > > > 账号冻结/封号与'聊天框显示请立即移动'无关，'聊天框显示请立即移动'是由于长时间没有操作，游戏自动下线。脚本不会自动下一局的问题正在修复。
> > > 
> > > 
> > > 已修复，下载最新版本
> > 
> > 
> > 16日最新版本出现同样问题，导致pvp被封24h
> 
> 你可以再额外添加一个单技能鼠标宏，比如10秒用一次2技能，只要能保证自己能死掉就行，这样有时候网络波动之类原因导致的脚本失效可以保证你当局游戏不会挂机结束，就不会导致封禁了

ok 到时候更新一下

**Comment by Jai-wei** [comment]
@tekkz123 @WJZhen 

20231123更新：
修复倒地重起后不再寻路的bug
新增原地不动25s后自动开启按键自鲨

**Comment by WJZhen** [comment]
> 1129版本，运行一段时间后失效，脚本停留在开始第36局游戏（没有输出读取地图id），聊天框显示请立即移动。attack与suicide文件均配置，attack中设置的按键可以正常触发，suicide中设置的自残技能（裁决蓝精英）没有观察到是否生效。本次是更新后第一次用，我和另一个朋友都是这个情况。

1209版本更新后再次因挂机冻结导致封号7天，两个号都是同一个原因，主要之前很长一段时间都没有出过类似问题，suicide中配置了释放裁决蓝精英自残
